### ISSUE TITLE
Delete functionality is not available in the UI

### ISSUE THREAD

**Issue by BishalPoudel149** [BITSAPIBP2024/TEAMA13#3]
As seen the product can't be removed once it is added, this might cause the bunch of unnecessary product to stays at the system 
![image](https://github.com/user-attachments/assets/4bcb89ca-4fe8-45df-bbde-6ae53da02b4b)

**Comment by Hahahaharsht** [comment]
Resolved with the commit "23cac2db630c7a470aac8e14ed0da695d103a58c "
Delete Button added
